$(function() {
	jQuery.extend(jQuery.validator.messages, { 
		required: "必填字段", 
		remote: "请修正该字段", 
		email: "请输入正确格式的电子邮件", 
		url: "请输入合法的网址", 
		date: "请输入合法的日期", 
		dateISO: "请输入合法的日期 (ISO).", 
		number: "请输入合法的数字", 
		digits: "只能输入整数", 
		creditcard: "请输入合法的信用卡号", 
		equalTo: "请再次输入相同的值", 
		accept: "请输入拥有合法后缀名的字符串", 
		maxlength: jQuery.validator.format("请输入一个长度最多是 {0} 的字符串"), 
		minlength: jQuery.validator.format("请输入一个长度最少是 {0} 的字符串"), 
		rangelength: jQuery.validator.format("请输入一个长度介于 {0} 和 {1} 之间的字符串"), 
		range: jQuery.validator.format("请输入一个介于 {0} 和 {1} 之间的值"), 
		max: jQuery.validator.format("请输入一个最大为 {0} 的值"), 
		min: jQuery.validator.format("请输入一个最小为 {0} 的值") 
	}); 
	
	 $.datepicker.regional['zh-CN'] = {   
        clearText: '清除',   
        clearStatus: '清除已选日期',   
        closeText: '关闭',   
        closeStatus: '不改变当前选择',   
        prevText: '<上月',   
        prevStatus: '显示上月',   
        prevBigText: '<<',   
        prevBigStatus: '显示上一年',   
        nextText: '下月>',   
        nextStatus: '显示下月',   
        nextBigText: '>>',   
        nextBigStatus: '显示下一年',   
        currentText: '今天',   
        currentStatus: '显示本月',   
        monthNames: ['一月','二月','三月','四月','五月','六月', '七月','八月','九月','十月','十一月','十二月'],   
        monthNamesShort: ['一','二','三','四','五','六', '七','八','九','十','十一','十二'],   
        monthStatus: '选择月份',   
        yearStatus: '选择年份',   
        weekHeader: '周',   
        weekStatus: '年内周次',   
        dayNames: ['星期日','星期一','星期二','星期三','星期四','星期五','星期六'],   
        dayNamesShort: ['周日','周一','周二','周三','周四','周五','周六'],   
        dayNamesMin: ['日','一','二','三','四','五','六'],   
        dayStatus: '设置 DD 为一周起始',   
        dateStatus: '选择 m月 d日, DD',   
        dateFormat: 'yy-mm-dd',   
        firstDay: 1,   
        initStatus: '请选择日期',
        changeMonth: true,
        changeYear: true,
        isRTL: false
	};   
	$.datepicker.setDefaults($.datepicker.regional['zh-CN']); 
});
